# Tổng quan đề tài

Bạn nhận được Cơ sở dữ liệu bóng đá châu Âu có hơn 25.000 trận đấu và hơn 10.000 cầu thủ cho các mùa bóng đá chuyên nghiệp châu Âu từ 2008 đến 2016. Mục tiêu là bạn xem qua cơ sở dữ liệu này và thực hiện phân tích, bao gồm một số bước khám phá dữ liệu, thống kê cơ bản và sau đó bạn hình dung kết quả. Để hoàn thành tất cả các bước, bạn cần truy vấn dữ liệu trong cơ sở dữ liệu bằng cách sử dụng câu lệnh SQL. Đề tài này thực hành bạn viết lệnh SQL để kéo dữ liệu về và trích xuất nó.

Tải dữ liệu bóng đá Châu Âu tại đây

# Mô tả dữ liệu

Cơ sở dữ liệu bóng đá châu Âu này có hơn 25.000 trận đấu và hơn 10.000 cầu thủ cho các mùa bóng đá chuyên nghiệp châu Âu từ 2008 đến 2016, 11 quốc gia châu Âu với chức vô địch dẫn đầu. Các thuộc tính của Người chơi và Đội có nguồn gốc từ loạt trò chơi video FIFA của EA Sports, bao gồm các bản cập nhật hàng tuần.

<table style="width: 100%;">
<tbody>
<tr>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">Table</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">Total Rows</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">Total Columns</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">Columns</span></p>
</td>
</tr>
<tr>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">Country</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">11</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">2</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">id, name</span></p>
</td>
</tr>
<tr>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">League</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">11</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">3</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">id, country_id, name</span></p>
</td>
</tr>
<tr>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">Match</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">25979</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">115</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">id, country_id, league_id, season, stage, date, match_api_id, home_team_api_id, away_team_api_id, home_team_goal, away_team_goal, home_player_X1, home_player_X2, home_player_X3, home_player_X4, home_player_X5, home_player_X6, home_player_X7, home_player_X8, home_player_X9, home_player_X10, home_player_X11, away_player_X1, away_player_X2, away_player_X3, away_player_X4, away_player_X5, away_player_X6, away_player_X7, away_player_X8, away_player_X9, away_player_X10, away_player_X11, home_player_Y1, home_player_Y2, home_player_Y3, home_player_Y4, home_player_Y5, home_player_Y6, home_player_Y7, home_player_Y8, home_player_Y9, home_player_Y10, home_player_Y11, away_player_Y1, away_player_Y2, away_player_Y3, away_player_Y4, away_player_Y5, away_player_Y6, away_player_Y7, away_player_Y8, away_player_Y9, away_player_Y10, away_player_Y11, home_player_1, home_player_2, home_player_3, home_player_4, home_player_5, home_player_6, home_player_7, home_player_8, home_player_9, home_player_10, home_player_11, away_player_1, away_player_2, away_player_3, away_player_4, away_player_5, away_player_6, away_player_7, away_player_8, away_player_9, away_player_10, away_player_11, goal, shoton, shotoff, foulcommit, card, cross, corner, possession, B365H, B365D, B365A, BWH, BWD, BWA, IWH, IWD, IWA, LBH, LBD, LBA, PSH, PSD, PSA, WHH, WHD, WHA, SJH, SJD, SJA, VCH, VCD, VCA, GBH, GBD, GBA, BSH, BSD, BSA</span></p>
</td>
</tr>
<tr>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">Player</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">11060</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">7</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">id, player_api_id, player_name, player_fifa_api_id, birthday, height, weight</span></p>
</td>
</tr>
<tr>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">Player_Attributes</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">183978</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">42</span></p>
</td>
<td>
<p><span style="font-family: arial, helvetica, sans-serif;">id, player_fifa_api_id, player_api_id, date, overall_rating, potential, preferred_foot, attacking_work_rate, defensive_work_rate, crossing, finishing, heading_accuracy,

# Gọi thư viện Python

In [2]:
#Import libraries
import numpy as np
import pandas as pd
import sqlite3
from datetime import timedelta
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 100)

## Câu hỏi 1: Kết nối tới cơ sở dữ liệu và truy vấn thông tin của tất cả các bảng

Đọc https://docs.python.org/2/library/sqlite3.html

Học viên chỉ sử dụng câu lệnh SQL để truy vấn kế quả, không được sử dụng câu lệnh Pandas để tính toán ra kết quả.

In [3]:
# Kết nối với cơ sở dữ liệu
conn = sqlite3.connect('./Data/database.sqlite')

# Lấy thông tin của tất cả bảng
tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Player_Attributes,Player_Attributes,11,"CREATE TABLE ""Player_Attributes"" (\n\t`id`\tIN..."
2,table,Player,Player,14,CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3,table,Match,Match,18,CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4,table,League,League,24,CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5,table,Country,Country,26,CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6,table,Team,Team,29,"CREATE TABLE ""Team"" (\n\t`id`\tINTEGER PRIMARY..."
7,table,Team_Attributes,Team_Attributes,2,CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

## Câu hỏi 2: Liệt kê các quốc gia có trong dữ liệu bảng "Country"

In [4]:
result = pd.read_sql("select * from country", conn)
result

       id         name
0       1      Belgium
1    1729      England
2    4769       France
3    7809      Germany
4   10257        Italy
5   13274  Netherlands
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

## Câu hỏi 3: Liệt kê các giải đấu trong bảng "League"

In [5]:
result = pd.read_sql("select * from league", conn)
result

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

## Câu hỏi 4: Liệt kê các giải đấu và thông tin quốc gia của từng league

Bảng League có quan hệ với bảng Country qua khóa country_id.

In [6]:
result = pd.read_sql(
    "select * from league l join country c on l.country_id = c.id", conn
)
result

       id  country_id                      name     id         name
0       1           1    Belgium Jupiler League      1      Belgium
1    1729        1729    England Premier League   1729      England
2    4769        4769            France Ligue 1   4769       France
3    7809        7809     Germany 1. Bundesliga   7809      Germany
4   10257       10257             Italy Serie A  10257        Italy
5   13274       13274    Netherlands Eredivisie  13274  Netherlands
6   15722       15722        Poland Ekstraklasa  15722       Poland
7   17642       17642  Portugal Liga ZON Sagres  17642     Portugal
8   19694       19694   Scotland Premier League  19694     Scotland
9   21518       21518           Spain LIGA BBVA  21518        Spain
10  24558       24558  Switzerland Super League  24558  Switzerland

## Câu hỏi 5: Liệt kê các trận đấu trong bảng  “Match”
- Khi một đội là chủ nhà, đội đó là "home team". Đội còn lại là "away team"
- Trong bảng Match, mỗi dòng dư liệu là một trận đấu của một đội chủ nhà và đội khách, tương ứng với kết quả ghi bàn đội nhà (home goal) và đội khách (away goal).

In [7]:
result = pd.read_sql("select * from match", conn)
result

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,...,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,...,195215.0,462944.0,563066.0,8800.0,67304.0,158253.0,133126.0,186524.0,93223.0,121115.0,232110.0,289732.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,1.0,3.0,5.0,7.0,2.0,4.0,6.0,8.0,5.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,...,37257.0,42276.0,114792.0,150007.0,178119.0,27232.0,570830.0,260708.0,201704.0,36382.0,34082.0,95257.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,...,289472.0,10637.0,67349.0,202663.0,32597.0,114794.0,188114.0,25840.0,482200.0,95230.0,451335.0,275122.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,1.0,2.0,4.0,6.0,8.0,3.0,7.0,5.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,...,178142.0,274776.0,121080.0,197757.0,260964.0,231614.0,113235.0,41116.0,462608.0,42262.0,92252.0,194532.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,...,71764.0,156175.0,95216.0,172768.0,22834.0,458806.0,207234.0,25772.0,40274.0,34035.0,41726.0,527103.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Câu hỏi 6: Liệt kê các trận đấu và thông tin về leage và country tương ứng

Bảng Match có quan hệ với :
 - Bảng Country thông qua khóa country_id
 - Bảng League thông qua khóa League_id

Sử dụng câu lệnh join để kết nối dư liệu từ 3 bảng trên.

In [9]:
result = pd.read_sql(
    "select * from match m join country c on m.country_id = c.id join league l on m.league_id = l.id",
    conn,
)
result

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,...,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA,id,name,id,country_id,name
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20,1,Belgium,1,1,Belgium Jupiler League
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60,1,Belgium,1,1,Belgium Jupiler League
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75,1,Belgium,1,1,Belgium Jupiler League
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50,1,Belgium,1,1,Belgium Jupiler League
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67,1,Belgium,1,1,Belgium Jupiler League
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,...,158253.0,133126.0,186524.0,93223.0,121115.0,232110.0,289732.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24558,Switzerland,24558,24558,Switzerland Super League
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,1.0,3.0,5.0,7.0,2.0,4.0,6.0,8.0,5.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,...,27232.0,570830.0,260708.0,201704.0,36382.0,34082.0,95257.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24558,Switzerland,24558,24558,Switzerland Super League
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,...,114794.0,188114.0,25840.0,482200.0,95230.0,451335.0,275122.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24558,Switzerland,24558,24558,Switzerland Super League
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,1.0,2.0,4.0,6.0,8.0,3.0,7.0,5.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,...,231614.0,113235.0,41116.0,462608.0,42262.0,92252.0,194532.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24558,Switzerland,24558,24558,Switzerland Super League
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,...,458806.0,207234.0,25772.0,40274.0,34035.0,41726.0,527103.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24558,Switzerland,24558,24558,Switzerland Super League

## Câu hỏi 7: Liệt kê số lượng trận đấu của mỗi giải đấu bao gồm cả tên giải đấu, sắp xếp theo thứ tự giảm dần số trận đấu

In [15]:
result = pd.read_sql(
    "select name, count(name) as 'SL' from match m join league l on m.league_id = l.id group by name order by name",
    conn,
)
result

                        name    SL
0     Belgium Jupiler League  1728
1     England Premier League  3040
2             France Ligue 1  3040
3      Germany 1. Bundesliga  2448
4              Italy Serie A  3017
5     Netherlands Eredivisie  2448
6         Poland Ekstraklasa  1920
7   Portugal Liga ZON Sagres  2052
8    Scotland Premier League  1824
9            Spain LIGA BBVA  3040
10  Switzerland Super League  1422

## Câu hỏi 8: Liệt kê tổng số bàn thắng của đội nhà và đội khách trong mỗi giải đấu
- Sử dụng câu lệnh Group By

In [21]:
result = pd.read_sql(
    "select league_id, sum(home_team_goal), sum(away_team_goal) from match group by league_id, home_team_goal, away_team_goal",
    conn,
)
result

     league_id  sum(home_team_goal)  sum(away_team_goal)
0            1                    0                    0
1            1                    0                  111
2            1                    0                  188
3            1                    0                   63
4            1                    0                   44
..         ...                  ...                  ...
475      24558                   30                    0
476      24558                   12                    2
477      24558                   30                   10
478      24558                   12                    6
479      24558                   14                    0

[480 rows x 3 columns]

## Câu hỏi 9: Liệt kê thông tin các đội từ bảng “Team”

In [22]:
result = pd.read_sql(
    "select * from team",
    conn,
)
result

        id  team_api_id  team_fifa_api_id      team_long_name team_short_name
0        1         9987             673.0            KRC Genk             GEN
1        2         9993             675.0        Beerschot AC             BAC
2        3        10000           15005.0    SV Zulte-Waregem             ZUL
3        4         9994            2007.0    Sporting Lokeren             LOK
4        5         9984            1750.0   KSV Cercle Brugge             CEB
..     ...          ...               ...                 ...             ...
294  49479        10190             898.0       FC St. Gallen             GAL
295  49837        10191            1715.0             FC Thun             THU
296  50201         9777             324.0         Servette FC             SER
297  50204         7730            1862.0  FC Lausanne-Sports             LAU
298  51606         7896               NaN              Lugano             LUG

[299 rows x 5 columns]

## Câu hỏi 10: Liệt kê 20 đội với số bàn thắng sân nhà cao nhất
- Sử dung câu lênh GROUP BY, LIMIT

In [33]:
result = pd.read_sql(
    "select team_long_name, sum(home_team_goal) from match m join team t on m.home_team_api_id = t.team_api_id group by team_long_name, home_team_goal order by sum(home_team_goal) desc limit 20",
    conn,
)
result

            team_long_name  sum(home_team_goal)
0             FC Barcelona                  120
1                 FC Basel                  120
2           Real Madrid CF                  120
3                  Chelsea                  110
4             FC Barcelona                  110
5                     Ajax                  108
6   Olympique de Marseille                  108
7           Real Madrid CF                  108
8                 FC Porto                  105
9          Manchester City                  105
10       Manchester United                  105
11                 Everton                  102
12               FC Twente                  100
13                  Napoli                  100
14                    Roma                  100
15             Valencia CF                  100
16      Olympique Lyonnais                   99
17         Atlético Madrid                   96
18                  Celtic                   96
19           VfL Wolfsburg                   96

## Câu hỏi 11: Liệt kê 20 đội có số bàn thắng trên sân khách cao nhất
- Sử dụng câu lênh GROUP BY, LIMIT

In [38]:
result = pd.read_sql(
    "select team_long_name, sum(away_team_goal) from match m join team t on m.away_team_api_id = t.team_api_id group by team_long_name, away_team_goal order by sum(away_team_goal) desc limit 20",
    conn,
)
result

       team_long_name  sum(away_team_goal)
0   Tottenham Hotspur                  104
1                Ajax                  102
2   Borussia Dortmund                   93
3              Celtic                   92
4                  AZ                   90
5             Arsenal                   90
6        FC Barcelona                   90
7            Juventus                   90
8               Milan                   90
9            FC Basel                   88
10           FC Porto                   87
11                PSV                   87
12             Celtic                   84
13     Real Madrid CF                   84
14               Roma                   84
15            Arsenal                   81
16               Roma                   81
17     Real Madrid CF                   80
18           FC Basel                   78
19          Feyenoord                   78

## Câu hỏi 12: Liệt kê tên các đội bóng và tổng số bàn thắng mỗi đội, sắp xếp  theo số lượng giảm dần

- Tổng số bàn thắng của một đội bao gồm cả số bàn thắng ở sân nhà và sân khách.
- Sử dụng câu lệnh Union

In [48]:
result = pd.read_sql(
    """select a.ten, sum(a.slbt) as bt from (select team_long_name as ten, sum(away_team_goal) as slbt from match m join team t on m.away_team_api_id = t.team_api_id group by team_long_name, away_team_goal  
    union 
    select team_long_name, sum(home_team_goal) from match m join team t on m.home_team_api_id = t.team_api_id group by team_long_name, home_team_goal) a group by a.ten""",
    conn,
)
result

                          ten   bt
0        1. FC Kaiserslautern   50
1                  1. FC Köln  226
2              1. FC Nürnberg  193
3             1. FSV Mainz 05  304
4                  AC Ajaccio   91
..                        ...  ...
291      Xerez Club Deportivo   28
292            Zagłębie Lubin  176
293         Zawisza Bydgoszcz   75
294  Évian Thonon Gaillard FC  141
295             Śląsk Wrocław  313

[296 rows x 2 columns]

## Câu hỏi 13: Liệt kê tên các đội bóng (long name) và tổng số trận đấu đội đó tham gia, sắp xếp theo thứ tự giảm dần.

In [62]:
result = pd.read_sql(
    "select team_long_name, count(*) as sl from match m join team t on m.home_team_api_id = t.team_api_id group by team_long_name order by team_long_name",
    conn,
)
result

               team_long_name   sl
0        1. FC Kaiserslautern   34
1                  1. FC Köln  102
2              1. FC Nürnberg   85
3             1. FSV Mainz 05  119
4                  AC Ajaccio   57
..                        ...  ...
291      Xerez Club Deportivo   19
292            Zagłębie Lubin   90
293         Zawisza Bydgoszcz   30
294  Évian Thonon Gaillard FC   76
295             Śląsk Wrocław  120

[296 rows x 2 columns]

## Câu hỏi 14: Liệt kê số trận thắng, thua và hòa của mỗi đội.

- Nếu một đội có số lượng bàn thắng trên sân nhà > số lượng bàn thắng trên sân khách của chính đội đó, thì đội đó sẽ "thắng" trong trận đấu này
- Nếu một đội có số lượng bàn thắng trên sân nhà < số lượng bàn thắng trên sân khách của chính đội đó, thì đội đó sẽ "thua" trong trận đấu này
- Nếu một đội có số lượng bàn thắng trên sân nhà = số lượng bàn thắng trên sân khách của chính đội đó, thì đội đó sẽ "hòa" trong trận đấu này
- Sử dụng câu lệnh "Case When"

In [70]:
result = pd.read_sql(
    """select a.team_long_name, a.info, count(*) as 'sl' from (select team_long_name, CASE
    WHEN home_team_goal > away_team_goal THEN 'Thang'
    WHEN home_team_goal < away_team_goal THEN 'Thua'
    ELSE 'Hoa'
    END AS info 
    
    from  match m join team t on m.home_team_api_id = t.team_api_id) a
    group by a.team_long_name, a.info
    """,
    conn,
)
result

               team_long_name   info  sl
0        1. FC Kaiserslautern    Hoa  11
1        1. FC Kaiserslautern  Thang   8
2        1. FC Kaiserslautern   Thua  15
3                  1. FC Köln    Hoa  31
4                  1. FC Köln  Thang  32
..                        ...    ...  ..
881  Évian Thonon Gaillard FC  Thang  29
882  Évian Thonon Gaillard FC   Thua  30
883             Śląsk Wrocław    Hoa  35
884             Śląsk Wrocław  Thang  59
885             Śląsk Wrocław   Thua  26

[886 rows x 3 columns]

## Câu hỏi 15: Liệt kê 10 đội có số trận thắng nhiều nhất

In [73]:
result = pd.read_sql(
    """select a.team_long_name, a.info, count(*) as 'sl' from (select team_long_name, CASE
    WHEN home_team_goal > away_team_goal THEN 'Thang'
    WHEN home_team_goal < away_team_goal THEN 'Thua'
    ELSE 'Hoa'
    END AS info 
    
    from  match m join team t on m.home_team_api_id = t.team_api_id) a
    where a.info = 'Thang'
    group by a.team_long_name, a.info
    order by count(*) desc
    limit 10
    """,
    conn,
)
result

      team_long_name   info   sl
0       FC Barcelona  Thang  131
1     Real Madrid CF  Thang  129
2             Celtic  Thang  120
3  Manchester United  Thang  116
4    Manchester City  Thang  113
5   FC Bayern Munich  Thang  109
6           Juventus  Thang  105
7                PSV  Thang  105
8               Ajax  Thang  103
9    Atlético Madrid  Thang  103

## Câu hỏi 16: Liệt kê tỉ lệ phần trăm về số trận của mỗi giải trên tổng tất cả các trận

In [130]:
result = pd.read_sql(
    """
    SELECT
        name,
        (COUNT(name) * 100.0 / (SELECT COUNT(*) FROM match)) AS percentage
    FROM 
        match m join league l on m.league_id = l.id
    GROUP BY 
        name
    order by percentage
    """,
    conn,
)


result

                        name  percentage
0   Switzerland Super League    5.473652
1     Belgium Jupiler League    6.651526
2    Scotland Premier League    7.021055
3         Poland Ekstraklasa    7.390585
4   Portugal Liga ZON Sagres    7.898687
5      Germany 1. Bundesliga    9.422995
6     Netherlands Eredivisie    9.422995
7              Italy Serie A   11.613226
8     England Premier League   11.701759
9             France Ligue 1   11.701759
10           Spain LIGA BBVA   11.701759

## Câu hỏi 17: Liệt kê tỉ lệ phần trăm về số bàn ghi được của từng giải so với tổng số bàn của tất cả các trận.

In [152]:
result = pd.read_sql(
    """SELECT
        name, (sum(home_team_goal) + sum(away_team_goal))*100.0/ (select sum(home_team_goal) + sum(away_team_goal) from match) as percentage
    FROM 
        match m join league l on m.league_id = l.id
    group by name
    order by percentage
    """,
    conn,
)
result

                        name  percentage
0   Switzerland Super League    5.927127
1         Poland Ekstraklasa    6.624269
2    Scotland Premier League    6.834834
3     Belgium Jupiler League    6.887476
4   Portugal Liga ZON Sagres    7.399661
5      Germany 1. Bundesliga   10.105709
6             France Ligue 1   10.566677
7     Netherlands Eredivisie   10.730292
8              Italy Serie A   11.232518
9     England Premier League   11.723363
10           Spain LIGA BBVA   11.968074

## Câu hỏi 18: Liệt kê tổng số bàn ghi được của từng giải đấu theo từng mùa giải.

In [156]:
result = pd.read_sql(
    """SELECT
        season, sum(home_team_goal) + sum(away_team_goal) as sl
    FROM 
        match m join league l on m.league_id = l.id
    group by season
    """,
    conn,
)
result

      season    sl
0  2008/2009  8672
1  2009/2010  8632
2  2010/2011  8749
3  2011/2012  8747
4  2012/2013  9039
5  2013/2014  8389
6  2014/2015  8897
7  2015/2016  9162

## Câu hỏi 19: Liệt kê thông tin cầu thủ:

- Quy đổi cân nặng sang kilogram
- Quy đổi chiều cao sang mét
- Tính chỉ số bmi = ( (weight* 0.453592) / (height/100)^2)
- Tính tuổi của cầu thủ

In [167]:
result = pd.read_sql(
    """
    SELECT *, (weight * 0.453592)/(height/100) as bmi, CAST((strftime('%Y', 'now') - strftime('%Y', birthday)) - (strftime('%m-%d', 'now') < strftime('%m-%d', birthday)) AS INT) AS age
    from player
    """,
    conn,
)
result

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight,bmi,age
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187,46.381072,32
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146,38.914345,34
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163,43.445467,33
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198,49.109370,42
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154,38.196177,44
...,...,...,...,...,...,...,...,...,...
11055,11071,26357,Zoumana Camara,2488,1979-04-03 00:00:00,182.88,168,41.668556,45
11056,11072,111182,Zsolt Laczko,164680,1986-12-18 00:00:00,182.88,176,43.652773,37
11057,11073,36491,Zsolt Low,111191,1979-04-29 00:00:00,180.34,154,38.734151,45
11058,11074,35506,Zurab Khizanishvili,47058,1981-10-06 00:00:00,185.42,172,42.076272,42
11059,11075,39902,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176,44.267601,41

## Câu hỏi 20: Liệt kê cầu thủ lớn tuổi nhất

In [170]:
result = pd.read_sql(
    """
    SELECT *, (weight * 0.453592)/(height/100) as bmi, CAST((strftime('%Y', 'now') - strftime('%Y', birthday)) - (strftime('%m-%d', 'now') < strftime('%m-%d', birthday)) AS INT) AS age
    from player
    order by age desc
    limit 1
    """,
    conn,
)
result

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight,bmi,age
0,290,39425,Alberto Fontana,2431,1967-01-23 00:00:00,185.42,161,39.385348,57

## Câu hỏi 21: Liệt kê  cầu thủ có số trận đấu nhiều nhất

In [174]:
result = pd.read_sql(
    """
    SELECT * from Player_Attributes
    """,
    conn,
)
result

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,63.0,41.0,45.0,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183974,102359,39902,2009-08-30 00:00:00,83.0,85.0,right,medium,low,84.0,77.0,59.0,89.0,77.0,84.0,86.0,78.0,84.0,85.0,66.0,72.0,77.0,86.0,73.0,76.0,58.0,72.0,67.0,81.0,56.0,78.0,86.0,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183975,102359,39902,2009-02-22 00:00:00,78.0,80.0,right,medium,low,74.0,76.0,53.0,84.0,77.0,85.0,86.0,74.0,73.0,86.0,66.0,67.0,77.0,74.0,73.0,75.0,58.0,66.0,65.0,73.0,61.0,64.0,72.0,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183976,102359,39902,2008-08-30 00:00:00,77.0,80.0,right,medium,low,74.0,71.0,53.0,84.0,77.0,85.0,86.0,74.0,73.0,86.0,66.0,67.0,77.0,74.0,73.0,75.0,58.0,66.0,65.0,73.0,67.0,64.0,72.0,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183977,102359,39902,2007-08-30 00:00:00,78.0,81.0,right,medium,low,74.0,64.0,57.0,86.0,77.0,87.0,86.0,73.0,73.0,91.0,61.0,60.0,77.0,69.0,73.0,72.0,58.0,67.0,59.0,78.0,63.0,63.0,68.0,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183978,102359,39902,2007-02-22 00:00:00,80.0,81.0,right,medium,low,74.0,68.0,57.0,88.0,77.0,87.0,86.0,53.0,78.0,91.0,58.0,64.0,77.0,66.0,73.0,72.0,58.0,67.0,59.0,78.0,63.0,63.0,68.0,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

## Câu hỏi 22: Liệt kê các cầu thủ có tổng số điểm đánh giá lớn hơn 80

In [178]:
result = pd.read_sql(
    """
    SELECT * from Player_Attributes
    where overall_rating > 80
    """,
    conn,
)
result

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,160,152747,30895,2013-03-15 00:00:00,81,82,right,high,medium,80,68,27,79,69.0,83,62.0,54,53,84,94,91,94.0,81,92.0,61,64.0,85,52,56,56,36,79,81.0,61,18,23,14.0,13,6,6,15,10
1,161,152747,30895,2013-02-15 00:00:00,81,82,right,high,medium,80,68,27,79,69.0,83,62.0,54,53,84,94,91,94.0,81,92.0,61,64.0,84,52,56,56,36,79,81.0,61,18,23,14.0,13,6,6,15,10
2,163,152747,30895,2012-02-22 00:00:00,81,84,right,high,medium,79,68,27,77,69.0,82,62.0,54,53,88,96,95,94.0,79,94.0,61,64.0,86,52,56,56,36,79,79.0,61,18,23,14.0,13,6,6,15,10
3,164,152747,30895,2011-08-30 00:00:00,82,83,right,high,medium,79,68,27,77,69.0,85,62.0,54,53,88,96,95,94.0,84,94.0,61,64.0,86,52,56,56,36,79,79.0,61,18,23,14.0,13,6,6,15,10
4,165,152747,30895,2011-02-22 00:00:00,82,85,right,high,medium,79,68,27,77,69.0,90,62.0,54,53,88,92,93,88.0,84,76.0,61,52.0,86,57,56,56,36,79,79.0,61,18,23,14.0,13,6,6,15,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7556,183970,102359,39902,2012-02-22 00:00:00,81,81,right,medium,low,80,72,59,86,77.0,80,86.0,78,81,82,59,63,81.0,74,70.0,78,58.0,50,62,81,51,32,77,87.0,78,22,31,30.0,9,13,8,15,5
7557,183971,102359,39902,2011-08-30 00:00:00,81,81,right,medium,low,80,72,59,86,77.0,80,86.0,78,81,82,60,63,81.0,74,70.0,78,58.0,50,62,81,51,32,77,87.0,78,22,31,30.0,9,13,8,15,5
7558,183972,102359,39902,2011-02-22 00:00:00,81,85,right,medium,low,81,78,59,85,77.0,80,88.0,78,82,84,65,69,77.0,83,73.0,78,58.0,71,70,83,56,32,84,87.0,73,22,31,30.0,9,13,8,15,5
7559,183973,102359,39902,2010-08-30 00:00:00,83,85,right,medium,low,84,78,59,87,77.0,84,86.0,78,84,85,65,69,77.0,86,73.0,78,58.0,71,70,83,56,32,84,88.0,73,22,31,30.0,9,13,8,15,5
7560,183974,102359,39902,2009-08-30 00:00:00,83,85,right,medium,low,84,77,59,89,77.0,84,86.0,78,84,85,66,72,77.0,86,73.0,76,58.0,72,67,81,56,78,86,88.0,83,22,31,30.0,9,20,84,20,20